"""empty message

Revision ID: 901084b34ef8
Revises: 
Create Date: 2022-12-19 15:59:58.157407

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '901084b34ef8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('China_datas',
    sa.Column('province', sa.Integer(), nullable=False),
    sa.Column('accu_diagnosis', sa.String(length=200), nullable=True),
    sa.Column('dead', sa.String(length=200), nullable=True),
    sa.Column('heal', sa.String(length=200), nullable=True),
    sa.Column('now_confirm', sa.String(length=200), nullable=True),
    sa.Column('deadRate', sa.String(length=200), nullable=True),
    sa.Column('healRate', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('province')
    )
    op.drop_table('china_datas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('china_datas',
    sa.Column('province', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('accu_diagnosis', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dead', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('heal', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('now_confirm', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('deadRate', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('healRate', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('province'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('China_datas')
    # ### end Alembic commands ###
